// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaXm3rSnL29IMLHxWpebSpEM-fl4V-wZc',
    appId: '1:227072994944:web:b5935aee63d04384100065',
    messagingSenderId: '227072994944',
    projectId: 'dropmate-84858',
    authDomain: 'dropmate-84858.firebaseapp.com',
    storageBucket: 'dropmate-84858.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2OzLVXdtChug3QLL_IAJD4uc8H1H4uYI',
    appId: '1:227072994944:android:3f8a9f41a5d781f7100065',
    messagingSenderId: '227072994944',
    projectId: 'dropmate-84858',
    storageBucket: 'dropmate-84858.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOtpG5yvhOq70WU9XA-8IAW4a_FLlKBY',
    appId: '1:227072994944:ios:72485c182fd39eb0100065',
    messagingSenderId: '227072994944',
    projectId: 'dropmate-84858',
    storageBucket: 'dropmate-84858.firebasestorage.app',
    iosBundleId: 'com.example.dropmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOtpG5yvhOq70WU9XA-8IAW4a_FLlKBY',
    appId: '1:227072994944:ios:72485c182fd39eb0100065',
    messagingSenderId: '227072994944',
    projectId: 'dropmate-84858',
    storageBucket: 'dropmate-84858.firebasestorage.app',
    iosBundleId: 'com.example.dropmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaXm3rSnL29IMLHxWpebSpEM-fl4V-wZc',
    appId: '1:227072994944:web:cd4d66c6185db5f2100065',
    messagingSenderId: '227072994944',
    projectId: 'dropmate-84858',
    authDomain: 'dropmate-84858.firebaseapp.com',
    storageBucket: 'dropmate-84858.firebasestorage.app',
  );
}
